### ISSUE TITLE
Error when testing the new connector

### ISSUE THREAD

**Issue by MagentoPro** [canelmas/kafka-connect-field-and-time-partitioner#11]
"org.apache.kafka.common.config.ConfigException: Invalid value -1 for configuration partition.duration.ms: Partition duration needs to be a positive. at io.confluent.connect.storage.partitioner.TimeBasedPartitioner.configure(TimeBasedPartitioner.java:117) at io.confluent.connect.s3.S3SinkTask.newPartitioner(S3SinkTask.java:207) at io.confluent.connect.s3.S3SinkTask.start(S3SinkTask.java:117) at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:309) at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186) at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:237) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829) "

**Comment by MagentoPro** [comment]
Problem is solved. Might be helpful to include configuration settings in the readme. Module will error out if you leave partition settings blank.
