### ISSUE TITLE
Missing installation documentation in README

### ISSUE THREAD

**Issue by joelvim** [canelmas/kafka-connect-field-and-time-partitioner#5]
I would like to use this plugin, but I get an error when creating a connector that uses it: 

```
java.lang.NullPointerException
connect           | 	at io.confluent.connect.storage.partitioner.PartitionerConfig.classNameEquals(PartitionerConfig.java:304)
connect           | 	at io.confluent.connect.storage.partitioner.PartitionerConfig.access$000(PartitionerConfig.java:33)
connect           | 	at io.confluent.connect.storage.partitioner.PartitionerConfig$PartitionerClassDependentsRecommender.visible(PartitionerConfig.java:249)
connect           | 	at org.apache.kafka.common.config.ConfigDef.validate(ConfigDef.java:615)
connect           | 	at org.apache.kafka.common.config.ConfigDef.validate(ConfigDef.java:623)
connect           | 	at org.apache.kafka.common.config.ConfigDef.validate(ConfigDef.java:531)
connect           | 	at org.apache.kafka.common.config.ConfigDef.validateAll(ConfigDef.java:514)
connect           | 	at org.apache.kafka.common.config.ConfigDef.validate(ConfigDef.java:496)
connect           | 	at org.apache.kafka.connect.connector.Connector.validate(Connector.java:144)
connect           | 	at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:375)
connect           | 	at org.apache.kafka.connect.runtime.AbstractHerder.lambda$validateConnectorConfig$1(AbstractHerder.java:326)
connect           | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
connect           | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
connect           | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
connect           | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
connect           | 	at java.base/java.lang.Thread.run(Thread.java:829)
```

I suppose that my plugin is not properly installed. I built the jar with `mvn package` and dropped it in the plugins folder. If this is not the correct way to do, could you add a documentation in the README for people that want to use this plugin?

**Comment by hamuelna** [comment]
I have just added a PR https://github.com/canelmas/kafka-connect-field-and-time-partitioner/pull/7 to improve the README need to wait for approval. But if you need it ASAP you can inspect my fork

**Comment by joelvim** [comment]
Thank you, I read your doc, and it is ok for me. I found the solution 2 days ago, and your doc confirms it. :+1:
